import sys
import csv
import datetime

from PyQt6.QtGui import QPixmap

import sqlite3
from PyQt6.QtWidgets import (QApplication, QMainWindow, QWidget, QTableWidgetItem, QHeaderView, QMessageBox)
import requests


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(532, 698)
        self.createButton = QtWidgets.QPushButton(parent=Form)
        self.createButton.setGeometry(QtCore.QRect(390, 650, 131, 31))
        self.createButton.setObjectName("createButton")
        self.layoutWidget = QtWidgets.QWidget(parent=Form)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 501, 360))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.manufacturerEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.manufacturerEdit.setObjectName("manufacturerEdit")
        self.horizontalLayout_3.addWidget(self.manufacturerEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.modelEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.modelEdit.setObjectName("modelEdit")
        self.horizontalLayout_4.addWidget(self.modelEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.priceEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.priceEdit.setObjectName("priceEdit")
        self.horizontalLayout_11.addWidget(self.priceEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.yearEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.yearEdit.setObjectName("yearEdit")
        self.horizontalLayout_6.addWidget(self.yearEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.colorEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.colorEdit.setObjectName("colorEdit")
        self.horizontalLayout_8.addWidget(self.colorEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.stateCombo = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.stateCombo.setObjectName("stateCombo")
        self.stateCombo.addItem("")
        self.stateCombo.addItem("")
        self.horizontalLayout_7.addWidget(self.stateCombo)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.privodCombo = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.privodCombo.setObjectName("privodCombo")
        self.privodCombo.addItem("")
        self.privodCombo.addItem("")
        self.privodCombo.addItem("")
        self.horizontalLayout_10.addWidget(self.privodCombo)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.kppCombo = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.kppCombo.setObjectName("kppCombo")
        self.kppCombo.addItem("")
        self.kppCombo.addItem("")
        self.kppCombo.addItem("")
        self.kppCombo.addItem("")
        self.horizontalLayout_9.addWidget(self.kppCombo)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.engineTypeCombo = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.engineTypeCombo.setObjectName("engineTypeCombo")
        self.engineTypeCombo.addItem("")
        self.engineTypeCombo.addItem("")
        self.engineTypeCombo.addItem("")
        self.engineTypeCombo.addItem("")
        self.engineTypeCombo.addItem("")
        self.horizontalLayout_12.addWidget(self.engineTypeCombo)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.ownerEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.ownerEdit.setObjectName("ownerEdit")
        self.horizontalLayout_13.addWidget(self.ownerEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.mileageEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.mileageEdit.setObjectName("mileageEdit")
        self.horizontalLayout_5.addWidget(self.mileageEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        # --- Интерьер ---
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_16 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_16.addWidget(self.label_16)

        self.interEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.interEdit.setObjectName("interEdit")
        self.horizontalLayout_16.addWidget(self.interEdit)

        # кнопка выбора файла (интерьер)
        self.chooseIntButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.chooseIntButton.setObjectName("chooseIntButton")
        self.chooseIntButton.setText("Открыть")
        self.horizontalLayout_16.addWidget(self.chooseIntButton)

        self.verticalLayout.addLayout(self.horizontalLayout_16)

        # --- Экстерьер ---
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_17 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_17.addWidget(self.label_17)

        self.exterEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.exterEdit.setObjectName("exterEdit")
        self.horizontalLayout_17.addWidget(self.exterEdit)

        # кнопка выбора файла (экстерьер)
        self.chooseExtButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.chooseExtButton.setObjectName("chooseExtButton")
        self.chooseExtButton.setText("Открыть")
        self.horizontalLayout_17.addWidget(self.chooseExtButton)

        self.verticalLayout.addLayout(self.horizontalLayout_17)

        self.formHInt = QtWidgets.QLabel(parent=Form)
        self.formHInt.setGeometry(QtCore.QRect(50, 650, 321, 30))
        self.formHInt.setText("")
        self.formHInt.setObjectName("formHInt")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(11, 390, 91, 21))
        self.label_2.setObjectName("label_2")
        self.descriptionEdit = QtWidgets.QLineEdit(parent=Form)
        self.descriptionEdit.setGeometry(QtCore.QRect(100, 390, 420, 250))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descriptionEdit.sizePolicy().hasHeightForWidth())
        self.descriptionEdit.setSizePolicy(sizePolicy)
        self.descriptionEdit.setObjectName("descriptionEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Форма объявления"))
        self.createButton.setText(_translate("Form", "Создать"))
        self.label_3.setText(_translate("Form", "Марка"))
        self.manufacturerEdit.setToolTip(_translate("Form", "<html><head/><body><p>Марка производителя машины(Mercedes, BMW, Audi и т.п.)</p></body></html>"))
        self.label_4.setText(_translate("Form", "Модель"))
        self.modelEdit.setToolTip(_translate("Form", "<html><head/><body><p>Модель машины с маркой (Cherry Tiggo 8 Pro Max 2.0 AMT</p></body></html>"))
        self.label_11.setText(_translate("Form", "Цена"))
        self.label_6.setText(_translate("Form", "Год выпуска"))
        self.label_8.setText(_translate("Form", "Цвет"))
        self.label_7.setText(_translate("Form", "Состояние"))
        self.stateCombo.setItemText(0, _translate("Form", "Битая"))
        self.stateCombo.setItemText(1, _translate("Form", "Не битая"))
        self.label_10.setText(_translate("Form", "Привод"))
        self.privodCombo.setItemText(0, _translate("Form", "Задний"))
        self.privodCombo.setItemText(1, _translate("Form", "Передний"))
        self.privodCombo.setItemText(2, _translate("Form", "Полный"))
        self.label_9.setText(_translate("Form", "Коробка передач"))
        self.kppCombo.setItemText(0, _translate("Form", "Механика"))
        self.kppCombo.setItemText(1, _translate("Form", "Автомат"))
        self.kppCombo.setItemText(2, _translate("Form", "Вариатор"))
        self.kppCombo.setItemText(3, _translate("Form", "Робот"))
        self.label_12.setText(_translate("Form", "Тип двигателя"))
        self.engineTypeCombo.setItemText(0, _translate("Form", "Бензин"))
        self.engineTypeCombo.setItemText(1, _translate("Form", "Газ"))
        self.engineTypeCombo.setItemText(2, _translate("Form", "Дизель"))
        self.engineTypeCombo.setItemText(3, _translate("Form", "Гибрид"))
        self.engineTypeCombo.setItemText(4, _translate("Form", "Электро"))
        self.label_13.setText(_translate("Form", "Владельцев по ПТС"))
        self.label_5.setText(_translate("Form", "Пробег"))
        self.label_16.setText(_translate("Form", "Путь к фото Интерьера"))
        self.label_17.setText(_translate("Form", "Путь к фото Экстерьера"))
        self.label_2.setText(_translate("Form", "Описание(HTML):"))

class Ui_OfferPage(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(670, 849)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.imageExt = QtWidgets.QLabel(parent=Form)
        self.imageExt.setText("")
        self.imageExt.setObjectName("imageExt")
        self.horizontalLayout_3.addWidget(self.imageExt)
        self.imageInt = QtWidgets.QLabel(parent=Form)
        self.imageInt.setText("")
        self.imageInt.setObjectName("imageInt")
        self.horizontalLayout_3.addWidget(self.imageInt)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.nameLabel = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout_4.addWidget(self.nameLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.modelLabel = QtWidgets.QLabel(parent=Form)
        self.modelLabel.setText("")
        self.modelLabel.setObjectName("modelLabel")
        self.verticalLayout_3.addWidget(self.modelLabel)
        self.manuLabel = QtWidgets.QLabel(parent=Form)
        self.manuLabel.setText("")
        self.manuLabel.setObjectName("manuLabel")
        self.verticalLayout_3.addWidget(self.manuLabel)
        self.yearLabel = QtWidgets.QLabel(parent=Form)
        self.yearLabel.setText("")
        self.yearLabel.setObjectName("yearLabel")
        self.verticalLayout_3.addWidget(self.yearLabel)
        self.colorLabel = QtWidgets.QLabel(parent=Form)
        self.colorLabel.setText("")
        self.colorLabel.setObjectName("colorLabel")
        self.verticalLayout_3.addWidget(self.colorLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.kppLabel = QtWidgets.QLabel(parent=Form)
        self.kppLabel.setText("")
        self.kppLabel.setObjectName("kppLabel")
        self.verticalLayout_2.addWidget(self.kppLabel)
        self.privodLabel = QtWidgets.QLabel(parent=Form)
        self.privodLabel.setText("")
        self.privodLabel.setObjectName("privodLabel")
        self.verticalLayout_2.addWidget(self.privodLabel)
        self.engineLabel = QtWidgets.QLabel(parent=Form)
        self.engineLabel.setText("")
        self.engineLabel.setObjectName("engineLabel")
        self.verticalLayout_2.addWidget(self.engineLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.stateLabel = QtWidgets.QLabel(parent=Form)
        self.stateLabel.setText("")
        self.stateLabel.setObjectName("stateLabel")
        self.verticalLayout.addWidget(self.stateLabel)
        self.ownersLabel = QtWidgets.QLabel(parent=Form)
        self.ownersLabel.setText("")
        self.ownersLabel.setObjectName("ownersLabel")
        self.verticalLayout.addWidget(self.ownersLabel)
        self.mileageLabel = QtWidgets.QLabel(parent=Form)
        self.mileageLabel.setText("")
        self.mileageLabel.setObjectName("mileageLabel")
        self.verticalLayout.addWidget(self.mileageLabel)
        self.creatorLabel = QtWidgets.QLabel(parent=Form)
        self.creatorLabel.setText("")
        self.creatorLabel.setObjectName("creatorLabel")
        self.verticalLayout.addWidget(self.creatorLabel)
        self.dateLabel = QtWidgets.QLabel(parent=Form)
        self.dateLabel.setText("")
        self.dateLabel.setObjectName("dateLabel")
        self.verticalLayout.addWidget(self.dateLabel)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.textEdit = QtWidgets.QTextEdit(parent=Form)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_4.addWidget(self.textEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.priceLabel = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.priceLabel.setFont(font)
        self.priceLabel.setText("")
        self.priceLabel.setObjectName("priceLabel")
        self.horizontalLayout_2.addWidget(self.priceLabel)
        self.callButton = QtWidgets.QPushButton(parent=Form)
        self.callButton.setObjectName("callButton")
        self.horizontalLayout_2.addWidget(self.callButton)
        self.buyButton = QtWidgets.QPushButton(parent=Form)
        self.buyButton.setObjectName("buyButton")
        self.horizontalLayout_2.addWidget(self.buyButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Объявление"))
        self.nameLabel.setText(_translate("Form", "TextLabel"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">asdasd</span></p></body></html>"))
        self.callButton.setText(_translate("Form", "Связаться с продавцом"))
        self.buyButton.setText(_translate("Form", "Купить"))

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 601))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.Search = QtWidgets.QWidget()
        self.Search.setObjectName("Search")
        self.searchTableWidget = QtWidgets.QTableWidget(parent=self.Search)
        self.searchTableWidget.setGeometry(QtCore.QRect(0, 100, 791, 431))
        self.searchTableWidget.setObjectName("searchTableWidget")
        self.searchTableWidget.setColumnCount(0)
        self.searchTableWidget.setRowCount(0)
        self.createNewButton = QtWidgets.QPushButton(parent=self.Search)
        self.createNewButton.setGeometry(QtCore.QRect(620, 530, 171, 23))
        self.createNewButton.setObjectName("createNewButton")
        self.label = QtWidgets.QLabel(parent=self.Search)
        self.label.setGeometry(QtCore.QRect(150, 0, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.Search)
        self.label_2.setGeometry(QtCore.QRect(360, 0, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.Search)
        self.label_3.setGeometry(QtCore.QRect(490, 0, 121, 16))
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(parent=self.Search)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 20, 781, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchBox = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.searchBox.setObjectName("searchBox")
        self.horizontalLayout.addWidget(self.searchBox)
        self.priceMin = QtWidgets.QLineEdit(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.priceMin.sizePolicy().hasHeightForWidth())
        self.priceMin.setSizePolicy(sizePolicy)
        self.priceMin.setObjectName("priceMin")
        self.horizontalLayout.addWidget(self.priceMin)
        self.priceMax = QtWidgets.QLineEdit(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.priceMax.sizePolicy().hasHeightForWidth())
        self.priceMax.setSizePolicy(sizePolicy)
        self.priceMax.setObjectName("priceMax")
        self.horizontalLayout.addWidget(self.priceMax)
        self.searchFilterBox = QtWidgets.QComboBox(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchFilterBox.sizePolicy().hasHeightForWidth())
        self.searchFilterBox.setSizePolicy(sizePolicy)
        self.searchFilterBox.setObjectName("searchFilterBox")
        self.searchFilterBox.addItem("")
        self.searchFilterBox.addItem("")
        self.searchFilterBox.addItem("")
        self.searchFilterBox.addItem("")
        self.searchFilterBox.addItem("")
        self.searchFilterBox.addItem("")
        self.horizontalLayout.addWidget(self.searchFilterBox)
        self.searchButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout.addWidget(self.searchButton)
        self.openOfferPageButton = QtWidgets.QPushButton(parent=self.Search)
        self.openOfferPageButton.setGeometry(QtCore.QRect(0, 530, 161, 23))
        self.openOfferPageButton.setObjectName("openOfferPageButton")
        self.widget = QtWidgets.QWidget(parent=self.Search)
        self.widget.setGeometry(QtCore.QRect(1, 50, 781, 43))
        self.widget.setObjectName("widget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_13 = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_4.addWidget(self.label_13)
        self.engineTypeCombo_2 = QtWidgets.QComboBox(parent=self.widget)
        self.engineTypeCombo_2.setObjectName("engineTypeCombo_2")
        self.engineTypeCombo_2.addItem("")
        self.engineTypeCombo_2.addItem("")
        self.engineTypeCombo_2.addItem("")
        self.engineTypeCombo_2.addItem("")
        self.engineTypeCombo_2.addItem("")
        self.verticalLayout_4.addWidget(self.engineTypeCombo_2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.privodCombo_2 = QtWidgets.QComboBox(parent=self.widget)
        self.privodCombo_2.setObjectName("privodCombo_2")
        self.privodCombo_2.addItem("")
        self.privodCombo_2.addItem("")
        self.privodCombo_2.addItem("")
        self.verticalLayout_5.addWidget(self.privodCombo_2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_9 = QtWidgets.QLabel(parent=self.widget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.kppCombo_2 = QtWidgets.QComboBox(parent=self.widget)
        self.kppCombo_2.setObjectName("kppCombo_2")
        self.kppCombo_2.addItem("")
        self.kppCombo_2.addItem("")
        self.kppCombo_2.addItem("")
        self.kppCombo_2.addItem("")
        self.verticalLayout_6.addWidget(self.kppCombo_2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_14 = QtWidgets.QLabel(parent=self.widget)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_7.addWidget(self.label_14)
        self.stateCombo_2 = QtWidgets.QComboBox(parent=self.widget)
        self.stateCombo_2.setObjectName("stateCombo_2")
        self.stateCombo_2.addItem("")
        self.stateCombo_2.addItem("")
        self.verticalLayout_7.addWidget(self.stateCombo_2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.Search, "")
        self.Account = QtWidgets.QWidget()
        self.Account.setObjectName("Account")
        self.loginWidget = QtWidgets.QWidget(parent=self.Account)
        self.loginWidget.setEnabled(True)
        self.loginWidget.setGeometry(QtCore.QRect(10, 180, 241, 151))
        self.loginWidget.setObjectName("loginWidget")
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.loginWidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 30, 190, 100))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.loginLogin = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.loginLogin.setObjectName("loginLogin")
        self.horizontalLayout_2.addWidget(self.loginLogin)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.loginPasswd = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.loginPasswd.setObjectName("loginPasswd")
        self.horizontalLayout_3.addWidget(self.loginPasswd)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.loginHint = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.loginHint.setText("")
        self.loginHint.setObjectName("loginHint")
        self.verticalLayout.addWidget(self.loginHint)
        self.loginCompleteButton = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.loginCompleteButton.setObjectName("loginCompleteButton")
        self.verticalLayout.addWidget(self.loginCompleteButton)
        self.signupWidget = QtWidgets.QWidget(parent=self.Account)
        self.signupWidget.setEnabled(True)
        self.signupWidget.setGeometry(QtCore.QRect(450, 70, 321, 331))
        self.signupWidget.setObjectName("signupWidget")
        self.layoutWidget2 = QtWidgets.QWidget(parent=self.signupWidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 100, 301, 184))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(parent=self.layoutWidget2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.signupLogin = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        self.signupLogin.setObjectName("signupLogin")
        self.horizontalLayout_4.addWidget(self.signupLogin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(parent=self.layoutWidget2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.signupPasswd = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        self.signupPasswd.setObjectName("signupPasswd")
        self.horizontalLayout_5.addWidget(self.signupPasswd)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(parent=self.layoutWidget2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.signupDisplayName = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        self.signupDisplayName.setObjectName("signupDisplayName")
        self.horizontalLayout_6.addWidget(self.signupDisplayName)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_12 = QtWidgets.QLabel(parent=self.layoutWidget2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.signupPhone = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        self.signupPhone.setObjectName("signupPhone")
        self.horizontalLayout_8.addWidget(self.signupPhone)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(parent=self.layoutWidget2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.signupCity = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        self.signupCity.setObjectName("signupCity")
        self.horizontalLayout_7.addWidget(self.signupCity)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.signupHint = QtWidgets.QLabel(parent=self.layoutWidget2)
        self.signupHint.setText("")
        self.signupHint.setObjectName("signupHint")
        self.verticalLayout_2.addWidget(self.signupHint)
        self.signupCompleteButton = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.signupCompleteButton.setObjectName("signupCompleteButton")
        self.verticalLayout_2.addWidget(self.signupCompleteButton)
        self.loggedAs = QtWidgets.QLabel(parent=self.Account)
        self.loggedAs.setGeometry(QtCore.QRect(250, 50, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.loggedAs.setFont(font)
        self.loggedAs.setObjectName("loggedAs")
        self.loginsignupWidget = QtWidgets.QWidget(parent=self.Account)
        self.loginsignupWidget.setGeometry(QtCore.QRect(270, 210, 141, 61))
        self.loginsignupWidget.setObjectName("loginsignupWidget")
        self.layoutWidget3 = QtWidgets.QWidget(parent=self.loginsignupWidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 0, 141, 54))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.loginButton = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.loginButton.setObjectName("loginButton")
        self.verticalLayout_3.addWidget(self.loginButton)
        self.sugnupButton = QtWidgets.QPushButton(parent=self.layoutWidget3)
        self.sugnupButton.setObjectName("sugnupButton")
        self.verticalLayout_3.addWidget(self.sugnupButton)
        self.tabWidget.addTab(self.Account, "")
        self.localOffers = QtWidgets.QWidget()
        self.localOffers.setObjectName("localOffers")
        self.myTableWidget = QtWidgets.QTableWidget(parent=self.localOffers)
        self.myTableWidget.setGeometry(QtCore.QRect(0, 30, 791, 531))
        self.myTableWidget.setObjectName("myTableWidget")
        self.myTableWidget.setColumnCount(0)
        self.myTableWidget.setRowCount(0)
        self.tabWidget.addTab(self.localOffers, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Покупка авто"))
        self.createNewButton.setText(_translate("MainWindow", "Создать новое объявление"))
        self.label.setText(_translate("MainWindow", "Поиск"))
        self.label_2.setText(_translate("MainWindow", "Цена от, руб"))
        self.label_3.setText(_translate("MainWindow", "Цена до, руб"))
        self.searchFilterBox.setItemText(0, _translate("MainWindow", "Модель"))
        self.searchFilterBox.setItemText(1, _translate("MainWindow", "Марка"))
        self.searchFilterBox.setItemText(2, _translate("MainWindow", "Пробег <"))
        self.searchFilterBox.setItemText(3, _translate("MainWindow", "Цвет"))
        self.searchFilterBox.setItemText(4, _translate("MainWindow", "Год выпуска"))
        self.searchFilterBox.setItemText(5, _translate("MainWindow", "Владельцев <"))
        self.searchButton.setText(_translate("MainWindow", "Поиск"))
        self.openOfferPageButton.setText(_translate("MainWindow", "Подробнее"))
        self.label_13.setText(_translate("MainWindow", "Тип двигателя"))
        self.engineTypeCombo_2.setItemText(0, _translate("MainWindow", "Бензин"))
        self.engineTypeCombo_2.setItemText(1, _translate("MainWindow", "Газ"))
        self.engineTypeCombo_2.setItemText(2, _translate("MainWindow", "Дизель"))
        self.engineTypeCombo_2.setItemText(3, _translate("MainWindow", "Гибрид"))
        self.engineTypeCombo_2.setItemText(4, _translate("MainWindow", "Электро"))
        self.label_4.setText(_translate("MainWindow", "Привод"))
        self.privodCombo_2.setItemText(0, _translate("MainWindow", "Задний"))
        self.privodCombo_2.setItemText(1, _translate("MainWindow", "Передний"))
        self.privodCombo_2.setItemText(2, _translate("MainWindow", "Полный"))
        self.label_9.setText(_translate("MainWindow", "Тип КПП"))
        self.kppCombo_2.setItemText(0, _translate("MainWindow", "Механика"))
        self.kppCombo_2.setItemText(1, _translate("MainWindow", "Автомат"))
        self.kppCombo_2.setItemText(2, _translate("MainWindow", "Вариатор"))
        self.kppCombo_2.setItemText(3, _translate("MainWindow", "Робот"))
        self.label_14.setText(_translate("MainWindow", "Состояние"))
        self.stateCombo_2.setItemText(0, _translate("MainWindow", "Битая"))
        self.stateCombo_2.setItemText(1, _translate("MainWindow", "Не битая"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Search), _translate("MainWindow", "Обзор"))
        self.label_5.setText(_translate("MainWindow", "Логин"))
        self.label_6.setText(_translate("MainWindow", "Пароль"))
        self.loginCompleteButton.setText(_translate("MainWindow", "Войти"))
        self.label_7.setText(_translate("MainWindow", "Логин"))
        self.label_8.setText(_translate("MainWindow", "Пароль"))
        self.label_11.setText(_translate("MainWindow", "Отображаемое имя"))
        self.label_12.setText(_translate("MainWindow", "Контактный номер телефона"))
        self.label_10.setText(_translate("MainWindow", "Город"))
        self.signupCompleteButton.setText(_translate("MainWindow", "Войти"))
        self.loggedAs.setText(_translate("MainWindow", "Вы вошли как:"))
        self.loginButton.setText(_translate("MainWindow", "Войти"))
        self.sugnupButton.setText(_translate("MainWindow", "Зарегистрироваться"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Account), _translate("MainWindow", "Аккаунт"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.localOffers), _translate("MainWindow", "Мои предложения"))



